apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/alex-zai/demo-app
  newTag: 642a257439b94260e9c022e2495406c91049b5a7
